name: 'Rebase Pulls'
description: 'Rebase pull requests in a repository'
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository'
    default: ${{ github.repository }}
  head:
    description: >
      Filter pull requests by head user or head organization and branch name in the format user:ref-name or organization:ref-name.
      For example: github:new-script-format or octocat:test-branch.
  base:
    description: >
      Filter pull requests by base branch name.
      Example: gh-pages.
  command-to-run-before-rebase:
    description: >
      Run this command within the branch before rebasing against `base`
  command-to-run-on-conflict:
    description: >
      Run this command when a conflict is found, and try to merge again.
  default-branch:
    description: >
      The default branch for the repo, defaults to master
    default: master
  handle-dependabot:
    description: >
      The Dependabot PR's require a PR Comment to rebase them.
      When this is `true` a comment will be added: `@dependabot rebase`
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
