name: 'Rebase'
description: 'Rebase pull requests in a repository'
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository'
    default: ${{ github.repository }}
  head:
    description: >
      Filter pull requests by head user or head organization and branch name in the format of user:ref-name or organization:ref-name.
      Example: peter-evans:test-branch or actions:patch-1
  base:
    description: >
      Filter pulls by base branch name.
      Example: master
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
