name: 'Rebase'
description: 'Rebase pull requests in a repository'
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository'
    default: ${{ github.repository }}
  committer:
    description: 'The committer name and email address.'
    default: GitHub <noreply@github.com>
  head:
    description: 'Filter pull requests by head branch name'
  base:
    description: 'Filter pull requests by base branch name'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
