name: CI
on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
     - uses: actions/cache@v1
       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
       with:
         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-
      - name: Install project dependencies
        run: yarn --prefer-offline
      - run: yarn run build-checkout
      - run: yarn run build
      - run: yarn run format-check
      - run: yarn run lint
      - run: yarn run test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: action.yml
          path: .

      - name: Rebase with head filter
        id: rebase1
        uses: ./
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: peter-evans/rebase-test-fixture-${{ matrix.target }}
          head: peter-evans:test-fixtures/1/head
      - if: steps.rebase1.outputs.rebased-count != 1
        run: exit 1

      - name: Rebase with base filter
        id: rebase2
        uses: ./
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: peter-evans/rebase-test-fixture-${{ matrix.target }}
          base: test-fixtures/2/base
      - if: steps.rebase2.outputs.rebased-count != 1
        run: exit 1

      - name: Rebase
        id: rebase3
        uses: ./
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: peter-evans/rebase-test-fixture-${{ matrix.target }}
      - if: steps.rebase3.outputs.rebased-count < 2
        run: exit 1

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update distribution
          title: Update distribution
          body: |
            - Updates the distribution for changes on `master`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
